version: '3.9'  # Specify Docker Compose version

services:
  app:
    build: .       # Build the Go app from a Dockerfile in the current directory
    ports:
      - 8080:8080  # Expose port 8080 for the Go app
